Repository wecode-bootcamp-korea/justcode-6-2nd-team4-front, pull requests merged in 2022-09, with the labels that each got.

#4 Feature: 메인 네비게이션바 UI
  src/assets/images/bag-shoe.png
  src/assets/images/carpentry.png
  src/assets/images/cat-toy.png
  src/assets/images/cutting-board.png
  src/assets/images/furniture.png
  src/assets/images/jewelry.png
  src/assets/images/leather.png
  src/assets/images/plant.png
  src/assets/images/pottery.png
  src/assets/images/teddy-bear.png
  src/assets/images/tools.png
  src/assets/images/wedding-rings.png
  src/pages/Main/Main.js
  src/pages/Main/Nav/DropDownMenu/DropDownMenu.js
  src/pages/Main/Nav/DropDownMenu/DropDownMenu.module.scss
  src/pages/Main/Nav/DropDownMenu/WorkMenu.js
  src/pages/Main/Nav/NavigationBar.js
  src/pages/Main/Nav/NavigationBar.module.scss
Labels: 💄 UI

#6 Feature: Global Style
  .prettierrc
  package-lock.json
  package.json
  src/Router.js
  src/components/HelmetProvider/HelmetProvider.js
  src/styles/GlobalStyles.js
Labels: 🧑‍🎨 Style, 💄 UI

#8 Feature: Header, Footer UI
  src/components/Footer/Footer.js
  src/components/Footer/Footer.module.scss
  src/components/Header/DropDown/DropDown.js
  src/components/Header/DropDown/DropDown.module.scss
  src/components/Header/Header.js
  src/components/Header/Header.module.scss
  src/components/Header/MyInfo/MyInfo.js
  src/components/Header/MyInfo/MyInfo.module.scss
  src/pages/Main/Main.js
Labels: 💄 UI

#10 Feature: 회원가입 UI
  .prettierrc
  package-lock.json
  package.json
  src/Router.js
  src/assets/images/bag-shoe.png
  src/assets/images/carpentry.png
  src/assets/images/cat-toy.png
  src/assets/images/cutting-board.png
  src/assets/images/furniture.png
  src/assets/images/jewelry.png
  src/assets/images/leather.png
  src/assets/images/logo.png
  src/assets/images/plant.png
  src/assets/images/pottery.png
  src/assets/images/teddy-bear.png
  src/assets/images/tools.png
  src/assets/images/wedding-rings.png
  src/components/Footer/Footer.js
  src/components/Footer/Footer.module.scss
  src/components/Header/DropDown/DropDown.js
  src/components/Header/DropDown/DropDown.module.scss
  src/components/Header/Header.js
  src/components/Header/Header.module.scss
  src/components/Header/MyInfo/MyInfo.js
  src/components/Header/MyInfo/MyInfo.module.scss
  src/components/HelmetProvider/HelmetProvider.js
  src/pages/Main/Main.js
  src/pages/Main/Nav/DropDownMenu/DropDownMenu.js
  src/pages/Main/Nav/DropDownMenu/DropDownMenu.module.scss
  src/pages/Main/Nav/DropDownMenu/WorkMenu.js
  src/pages/Main/Nav/NavigationBar.js
  src/pages/Main/Nav/NavigationBar.module.scss
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.module.scss
  src/styles/GlobalStyles.js
Labels: 💄 UI

#12 Feature: 회원가입 UI
  src/Router.js
  src/assets/images/logo.png
  src/components/Footer/Footer.js
  src/components/Header/Header.js
  src/components/Header/Header.module.scss
  src/pages/Signup/Signup.js
  src/pages/Signup/Signup.module.scss
Labels: 💄 UI

#13 Feature: 메인페이지 이미지슬라이더 구현
  package-lock.json
  package.json
  src/Router.js
  src/assets/images/banner-1.png
  src/assets/images/banner-2.png
  src/assets/images/banner-3.png
  src/components/Header/Header.js
  src/components/MainImageSlider/ImageSlider.js
  src/components/MainImageSlider/ImageSlider.scss
  src/components/NavigationBar/DropDownMenu.js
  src/components/NavigationBar/DropDownMenu.module.scss
  src/components/NavigationBar/NavigationBar.js
  src/components/NavigationBar/NavigationBar.module.scss
  src/components/NavigationBar/WorkMenu.js
  src/index.js
  src/pages/Main/Main.js
  src/pages/Main/Nav/DropDownMenu/DropDownMenu.module.scss
Labels: 💄 UI

#16 Feature: 메인 페이지 아이템 리스트
  public/mocks/MainPage/new.json
  src/assets/images/next.png
  src/assets/images/prev.png
  src/assets/images/star.png
  src/components/Header/Header.js
  src/components/ItemCard/ItemCard.js
  src/components/ItemCard/ItemCard.module.scss
  src/components/MainImageSlider/ImageSlider.js
  src/components/MainItemList/MainItemList.js
  src/components/MainItemList/MainItemList.module.scss
  src/pages/Main/Main.js
Labels: ✨ Feature, 💄 UI

#18 Feature: 메인화면 통신
  src/components/ItemCard/ItemCard.js
  src/components/ItemCard/ItemCard.module.scss
  src/components/MainItemList/MainItemList.js
  src/components/MainItemList/MainItemList.module.scss
Labels: ✨ Feature, 💄 UI

#22 Feature/category
  public/mocks/Category/categoryItemList.json
  src/Router.js
  src/components/ItemCard/ItemCard.module.scss
  src/components/NavigationBar/DropDownMenu.js
  src/components/NavigationBar/DropDownMenu.module.scss
  src/components/NavigationBar/NavigationBar.js
  src/components/NavigationBar/NavigationBar.module.scss
  src/pages/Category/Category.js
  src/pages/Category/Category.module.scss
Labels: ✨ Feature, 💄 UI

#25 Feature/cart
  public/mocks/Cart/CartList.json
  public/mocks/Developer/Developers.json
  public/mocks/Developer/heayeon.png
  public/mocks/Developer/jieun.png
  public/mocks/Developer/seungseop.jpg
  public/mocks/Developer/seyoung.png
  public/mocks/Developer/yuhyeon.png
  src/Router.js
  src/assets/images/x.png
  src/components/Cart/CartList.js
  src/components/Cart/CartList.module.scss
  src/components/Cart/CartPayment.js
  src/components/Cart/CartPayment.module.scss
  src/components/ItemCard/ItemCard.js
  src/components/ItemCard/ItemCard.module.scss
  src/components/NavigationBar/DropDownMenu.js
  src/components/NavigationBar/DropDownMenu.module.scss
  src/components/NavigationBar/NavigationBar.js
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.module.scss
  src/pages/Category/Category.js
  src/pages/Developers/Developers.js
  src/pages/Developers/Developers.module.scss
Labels: ✨ Feature, 💄 UI, 🐛 Bug

#19 Feature: 제품 상세 화면 작업
  package-lock.json
  package.json
  public/mocks/ProductDetail/product1.json
  public/mocks/ProductDetail/product2.json
  public/mocks/ProductDetail/reviews.json
  src/Router.js
  src/assets/svgs/close.svg
  src/assets/svgs/heart.svg
  src/assets/svgs/heart_red.svg
  src/assets/svgs/notice.svg
  src/assets/svgs/share.svg
  src/assets/svgs/star.svg
  src/components/Product/ProductContainer.js
  src/components/Product/ProductContainer.module.scss
  src/components/Product/ProductContent/ProductContent.js
  src/components/Product/ProductContent/ProductContent.module.scss
  src/components/Product/ProductDeliveryInfo/ProductDeliveryInfo.js
  src/components/Product/ProductDeliveryInfo/ProductDeliveryInfo.module.scss
  src/components/Product/ProductDeliveryInfo/ProductDeliveryInfoContainer.js
  src/components/Product/ProductDeliveryInfo/ProductDeliveryInfoContainer.module.scss
  src/components/Product/ProductDetailContainer.js
  src/components/Product/ProductDetailContainer.module.scss
  src/components/Product/ProductImage/ProductImage.js
  src/components/Product/ProductImage/ProductImage.module.scss
  src/components/Product/ProductInfo/ProductInfo.js
  src/components/Product/ProductInfo/ProductInfo.module.scss
  src/components/Product/ProductInfo/ProductInfoContainer.js
  src/components/Product/ProductInfo/ProductInfoContainer.module.scss
  src/components/Product/ProductOptions/ProductOptions.js
  src/components/Product/ProductOptions/ProductOptions.module.scss
  src/components/Product/ProductOptions/ProductOptionsItem.js
  src/components/Product/ProductOptions/ProductOptionsItem.module.scss
  src/components/Product/ProductOptions/ProductOptionsItemSelectedInfo.js
  src/components/Product/ProductOptions/ProductOptionsItemSelectedInfo.module.scss
  src/components/Product/ProductOptions/ProductOptionsItemSelectedInfoContainer.js
  src/components/Product/ProductOptions/ProductOptionsItemSelectedInfoContainer.module.scss
  src/components/Product/ProductPurchase/ProductPurchase.js
  src/components/Product/ProductPurchase/ProductPurchase.module.scss
  src/components/Product/ProductReviews/ProductReviews.js
  src/components/Product/ProductReviews/ProductReviews.module.scss
  src/components/Product/SellerInfo/SellerInfo.js
  src/components/Product/SellerInfo/SellerInfo.module.scss
  src/config.js
  src/pages/ProductDetail/Api.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.module.scss
  src/pages/ProductDetail/ProductDetailProvider.js
  src/pages/ProductDetail/constants/deliveryTopic.js
  src/pages/ProductDetail/hooks/useMoveScroll.js
  src/pages/ProductDetail/redux/optionsSlice.js
  src/pages/ProductDetail/redux/productSlice.js
  src/pages/ProductDetail/redux/productStore.js
  src/pages/ProductDetail/redux/reviewsSlice.js
  src/pages/ProductDetail/schemas/productOptionsSchema.js
  src/pages/ProductDetail/schemas/productReviewsSchema.js
  src/pages/ProductDetail/schemas/productSchema.js
Labels: 🔨 Refactor, 🎨 Modify, ✨ Feature, 💄 UI, 🐛 Bug

#34 Fix/cart
  package-lock.json
  src/Router.js
  src/components/Cart/CartList.js
  src/components/Cart/CartPayment.js
  src/components/ItemCard/ItemCard.js
  src/components/MainItemList/MainItemList.js
  src/components/MyPageComp/Info/MyPageInfo.module.scss
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.module.scss
  src/pages/Category/Category.js
Labels: 🐛 Bug

#36 Fix: 제품 상세 화면 버그 수정
  src/components/Product/ProductImage/ProductImage.module.scss
  src/components/Product/ProductPurchase/ProductPurchase.js
  src/components/Product/ProductReviews/ProductReviews.module.scss
  src/components/Product/SellerInfo/SellerInfo.module.scss
  src/pages/ProductDetail/Api.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/redux/optionsSlice.js
Labels: 🎨 Modify, 🐛 Bug

#37 Fix:main, category, cart
  src/components/Cart/CartList.js
  src/components/Cart/CartList.module.scss
  src/components/Cart/CartPayment.module.scss
  src/components/NavigationBar/DropDownMenu.js
  src/components/NavigationBar/DropDownMenu.module.scss
  src/components/NavigationBar/NavigationBar.js
  src/components/NavigationBar/NavigationBar.module.scss
Labels: 🎨 Modify

#38 Fix: CartList 배송비 코드 수정
  src/components/Cart/CartList.js
Labels: 🐛 Bug
